services:
    Netmex\RequestBundle\:
        resource: "../src/"
        autowire: true
        autoconfigure: true
        exclude: "../src/{Entity,Tests}"

    Netmex\RequestBundle\ArgumentResolver\RequestArgumentResolver:
        tags:
            - { name: "controller.argument_value_resolver" }
        arguments:
            $parameterFactory: '@Netmex\RequestBundle\Factory\ParameterFactory'


    Netmex\RequestBundle\Factory\ParameterFactory:
        arguments:
            $validator: "@validator"
            $caster: '@Netmex\RequestBundle\Caster\TypeCaster'

    Netmex\RequestBundle\Request\AbstractRequest:
        arguments:
            $parameterFactory: '@Netmex\RequestBundle\Factory\ParameterFactory'
